/*
    날짜 : 2024/03/07
    이름 : 남가희
    내용 : PL&SQL 실습하기

*/

--실습하기 1-1
set serveroutput on;
begin
    dbms_output.put_line('Hello Oracle');
end;

--실습하기 1-2
DECLARE
 NO NUMBER(4) := 1001;
 NAME VARCHAR2(10) := '홍길동';
 HP CHAR(13) := '010-1000-1001';
 ADDR VARCHAR2(100) := '부산광역시';
BEGIN
 --DBMS_OUTPUT.PUT_LINE('번호 : ' || NO);
 DBMS_OUTPUT.PUT_LINE('이름 : ' || NAME);
 DBMS_OUTPUT.PUT_LINE('전화 : ' || HP);
 DBMS_OUTPUT.PUT_LINE('주소 : ' || ADDR);
END;

SET SERVEROUTPUT ON;
DECLARE
 NO CONSTANT NUMBER(4) := 1001;
 NAME VARCHAR2(10);
 HP CHAR(13) := '000-0000-0000';
 AGE NUMBER(2) DEFAULT 1;
 ADDR VARCHAR2(10) NOT NULL := '부산';
BEGIN
 NAME := '김유신';
 HP := '010-1000-1001';
 DBMS_OUTPUT.PUT_LINE('번호 : ' || NO);
 DBMS_OUTPUT.PUT_LINE('이름 : ' || NAME);
 DBMS_OUTPUT.PUT_LINE('전화 : ' || HP);
 DBMS_OUTPUT.PUT_LINE('나이 : ' || AGE);
 DBMS_OUTPUT.PUT_LINE('주소 : ' || ADDR);
END;

DECLARE
 NO DEPT.DEPTNO%TYPE;
 NAME DEPT.DNAME%TYPE;
 ADDR DEPT.LOC%TYPE;
BEGIN
 SELECT *
 INTO NO, NAME, ADDR
 FROM DEPT
 WHERE DEPTNO = 30;
 DBMS_OUTPUT.PUT_LINE('부서번호 : ' || NO);
 DBMS_OUTPUT.PUT_LINE('부서명 : ' || NAME);
 DBMS_OUTPUT.PUT_LINE('주소 : ' || ADDR);
END;

DECLARE
 -- 선언
 ROW_DEPT DEPT%ROWTYPE;
BEGIN
 -- 처리
 SELECT *
 INTO ROW_DEPT
 FROM DEPT
 WHERE DEPTNO = 40;

 -- 출력
 DBMS_OUTPUT.PUT_LINE('부서번호 : ' || ROW_DEPT.DEPTNO);
 DBMS_OUTPUT.PUT_LINE('부서명 : ' || ROW_DEPT.DNAME);
 DBMS_OUTPUT.PUT_LINE('주소 : ' || ROW_DEPT.LOC);
END;

-- 테이블 복사(데이터 제외)
CREATE TABLE DEPT_RECORD AS SELECT * FROM DEPT WHERE 1 = 0;
DECLARE
TYPE REC_DEPT IS RECORD (
deptno NUMBER(2),
dname DEPT.DNAME%TYPE,
loc DEPT.LOC%TYPE
);
dept_rec REC_DEPT;
BEGIN
dept_rec.deptno := 10;
dept_rec.dname := '개발부';
dept_rec.loc := '부산';
INSERT INTO DEPT_RECORD VALUES dept_rec;
DBMS_OUTPUT.PUT_LINE('PL/SQL 종료...');
END;

DECLARE
TYPE REC_DEPT IS RECORD (
deptno DEPT.DEPTNO%TYPE,
dname DEPT.DNAME%TYPE,
loc DEPT.LOC%TYPE
);
TYPE REC_EMP IS RECORD (
empno EMP.EMPNO%TYPE,
ename EMP.ENAME%TYPE,
dinfo REC_DEPT
);
emp_rec REC_EMP;
BEGIN
SELECT E.EMPNO, E.ENAME, D.DEPTNO, D.DNAME, D.LOC
INTO
emp_rec.empno,
emp_rec.ename,
emp_rec.dinfo.deptno,
emp_rec.dinfo.dname,
emp_rec.dinfo.loc
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO AND E.EMPNO = 7788;
DBMS_OUTPUT.PUT_LINE('EMPNO : ' || emp_rec.empno);
DBMS_OUTPUT.PUT_LINE('ENAME : ' || emp_rec.ename);
DBMS_OUTPUT.PUT_LINE('DEPTNO : ' || emp_rec.dinfo.deptno);
DBMS_OUTPUT.PUT_LINE('DNAME : ' || emp_rec.dinfo.dname);
DBMS_OUTPUT.PUT_LINE('LOC : ' || emp_rec.dinfo.loc);
DBMS_OUTPUT.PUT_LINE('PL/SQL 종료...');
END;

--실습 3-1
declare 
    num number:=0;
begin 
    while num <4 loop
    dbms_output.put_line('num : '||num);
    num
    



--실습 3-2
DECLARE
NUM NUMBER := -1;
BEGIN
IF NUM > 0 THEN
DBMS_OUTPUT.PUT_LINE('NUM은 0보다 크다.');
ELSE
DBMS_OUTPUT.PUT_LINE('NUM은 0보다 작다.');
END IF;
DBMS_OUTPUT.PUT_LINE('PL/SQL 종료...');
END;
--실습 3-3
DECLARE
SCORE NUMBER := 86;
BEGIN
IF SCORE >= 90 AND SCORE <= 100 THEN
DBMS_OUTPUT.PUT_LINE('A 입니다.');
ELSIF SCORE >= 80 AND SCORE < 90 THEN
DBMS_OUTPUT.PUT_LINE('B 입니다.');
ELSIF SCORE >= 70 AND SCORE < 80 THEN
DBMS_OUTPUT.PUT_LINE('C 입니다.');
ELSIF SCORE >= 60 AND SCORE < 70 THEN
DBMS_OUTPUT.PUT_LINE('D 입니다.');
ELSE
DBMS_OUTPUT.PUT_LINE('F 입니다.');
END IF;
DBMS_OUTPUT.PUT_LINE('PL/SQL 종료...');
END;
--실습 3-4
DECLARE
SCORE NUMBER := 86;
BEGIN
CASE FLOOR(SCORE/10)
WHEN 9 THEN DBMS_OUTPUT.PUT_LINE('A 입니다.');
WHEN 8 THEN DBMS_OUTPUT.PUT_LINE('B 입니다.');
WHEN 7 THEN DBMS_OUTPUT.PUT_LINE('C 입니다.');
WHEN 6 THEN DBMS_OUTPUT.PUT_LINE('D 입니다.');
ELSE DBMS_OUTPUT.PUT_LINE('F 입니다.');
END CASE;
DBMS_OUTPUT.PUT_LINE('PL/SQL 종료...');
END;
--실습 3-5
DECLARE
NUM NUMBER := 0;
BEGIN
LOOP
DBMS_OUTPUT.PUT_LINE('NUM : ' || NUM);
NUM := NUM + 1;
IF NUM > 3 THEN
EXIT;
END IF;
END LOOP;
DBMS_OUTPUT.PUT_LINE('PL/SQL 종료...');
END;
--실습 3-6
BEGIN
FOR i IN 1..3 LOOP
DBMS_OUTPUT.PUT_LINE('i : ' || i);
END LOOP;
DBMS_OUTPUT.PUT_LINE('PL/SQL 종료...');
END;
--실습 3-7
DECLARE
NUM NUMBER := 0;
BEGIN
WHILE NUM < 4 LOOP
DBMS_OUTPUT.PUT_LINE('NUM : ' || NUM);
NUM := NUM + 1;
END LOOP;
DBMS_OUTPUT.PUT_LINE('PL/SQL 종료...');
END;
--실습 3-8
DECLARE
NUM NUMBER := 0;
BEGIN
WHILE NUM < 5 LOOP
NUM := NUM + 1;
-- MOD(): 나머지를 구하는 SQL함수 IF MOD(NUM, 2) = 0 THEN
CONTINUE;
END IF;
DBMS_OUTPUT.PUT_LINE('NUM : ' || NUM);
END LOOP;
DBMS_OUTPUT.PUT_LINE('PL/SQL 종료...');
END;
--실습 3-9
BEGIN
FOR i IN 1..5 LOOP
CONTINUE WHEN MOD(i, 2) = 0;
DBMS_OUTPUT.PUT_LINE('i : ' || i);
END LOOP;
DBMS_OUTPUT.PUT_LINE('PL/SQL 종료...');
END;



    

